source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0' 

target 'BSImagePicker_Example' do
  pod "BSImagePicker", :path => "../"
end

target 'BSImagePicker_Tests' do
  pod "BSImagePicker", :path => "../"
end

