source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!
workspace '../BSImagePicker'


target 'Example' do
  project '../Example'
  pod 'BSImagePicker', :path => '../'
end
